GET http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZWtzYW5kciIsImlkIjoiNjBlM2ZjZDY3ZTQ5MTMyMjA4NmIyMGY0IiwiaWF0IjoxNjI1NTcwNjk3LCJleHAiOjE2MjU2MDY2OTd9.VRJhOTaePPQWthT5p89GGIrpsWdu0yzzTbML9q2Nvxk


###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

